replicaCount: 1

image:
  repository: art-hq.intranet.qualys.com:5001/k8s.gcr.io/spark-ui-proxy
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePortUI: 30007

ingress:
  enabled: false
  
resources:
  requests:
    cpu: 100m

nodeSelector:
  role: support

tolerations: []

affinity: {}
