apiVersion: v1
kind: Service
metadata:
  name: {{ template "hiveserver.name" . }}
  labels:
    app: {{ template "hiveserver.name" . }}
    chart: {{ template "hiveserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portHTTP }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "hiveserver.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hiveserver.fullname" . }}
  labels:
    app: {{ template "hiveserver.name" . }}
    chart: {{ template "hiveserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.portUI }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    app: {{ template "hiveserver.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: zeppelin-external
  labels:
    app: zeppelin-external
    chart: {{ template "hiveserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.portHTTP }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "hiveserver.name" . }}
    release: {{ .Release.Name }}