apiVersion: v1
kind: Service
metadata:
  name: alluxio-master-external
  labels:
    app: alluxio-external
spec:
  ports:
  - port: 19998
    name: rpc
    nodePort: {{ .Values.service.nodePortRPC }}
  - port: 19999
    name: web
    nodePort: {{ .Values.service.nodePortUI }}
  type: NodePort
  selector:
    app: alluxio-master