apiVersion: v1
kind: Service
metadata:
  name: alluxio-master-external
  labels:
    app: alluxio-external
spec:
  ports:
  - port: 19998
    name: rpc
    nodePort: 31001
  - port: 19999
    name: web
    nodePort: 31002
  type: NodePort
  selector:
    app: alluxio-master
