apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: alluxio-worker
spec:
  template:
    metadata:
      labels:
        name: alluxio-worker
        app: alluxio
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        role: storage
      containers:
        - name: alluxio-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          pullPolicy: {{ .Values.image.pullPolicy | quote }}
          resources:
            requests:
              cpu: "0.5"
              memory: "2G"
            limits:
              cpu: "1"
              memory: "2G"
          command: ["/entrypoint.sh"]
          args: ["worker"]
          env:
          - name: ALLUXIO_WORKER_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          envFrom:
          - configMapRef:
              name: alluxio-config
          ports:
          - containerPort: 29998
            name: rpc
          - containerPort: 29999
            name: data
          - containerPort: 29996
            name: web
          securityContext:
            privileged: true
          volumeMounts:
            - name: alluxio-ramdisk
              mountPath: /dev/shm
            - name: alluxio-domain
              mountPath: /opt/domain
      restartPolicy: Always
      volumes:
        - name: alluxio-ramdisk
          emptyDir:
            medium: "Memory"
            sizeLimit: "1G"
        - name: alluxio-domain
          hostPath:
            path: /tmp/domain
            type: Directory
