replicaCount:
  mon: 3

image:
  toolbox:
    repository: art-hq.intranet.qualys.com:5001/k8s.gcr.io/rook/ceph-toolbox
    tag: master
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector:
  all:
    key: role
    value: storage

tolerations: []

affinity: {}

namespaces:
  operator: rook-ceph-system
  cluster: rook-ceph

serviceAccount: rook-ceph-cluster