replicaCount: 1

image:
  repository: art-hq.intranet.qualys.com:5001/k8s.gcr.io/hiveserver
  tag: 0.1.33
  pullPolicy: IfNotPresent

service:
  type: None
  portHTTP: 10001
  portUI: 10002
  nodePortUI: 30004
  nodePortHTTP: 30005

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m

nodeSelector:
  role: support

tolerations: []

affinity: {}
