replicaCount: 3

image:
  repository: art-hq.intranet.qualys.com:5001/k8s.gcr.io/spark
  tag: 2.3.1_v7
  pullPolicy: IfNotPresent
  command: ["/start-worker"]

service: {}

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m

nodeSelector:
  role: compute

tolerations: []

affinity: {}
  # requiredDuringSchedulingIgnoredDuringExecution:
  #   nodeSelectorTerms:
  #   - matchExpressions:
  #     - key: role
  #       operator: In
  #       values:
  #       - compuasdasd
