replicaCount: 5

image:
  repository: art-hq.intranet.qualys.com:5001/k8s.gcr.io/spark
  tag: 0.1.18
  pullPolicy: IfNotPresent
  command: ["/start-worker"]

service: {}

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m

nodeSelector:
  role: compute

tolerations: []

affinity: {}
