replicaCount: 1

image:
  repository: art-hq.intranet.qualys.com:5001/k8s.gcr.io/alluxio
  tag: 0.3.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  nodePortRPC: 30001
  nodePortUI: 30002

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
