apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark-hadoop-master.name" . }}
  labels:
    app: {{ template "spark-hadoop-master.name" . }}
    chart: {{ template "spark-hadoop-master.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portUI }}
      targetPort: webui
      protocol: TCP
      name: webui
    - port: {{ .Values.service.portRPC }}
      targetPort: rpc 
      name: rpc
  selector:
    app: {{ template "spark-hadoop-master.name" . }}
    release: {{ .Release.Name }}
